/*
 * Motor_DC.c
 *
 *  Created on: Mar 26, 2024
 *      Author: User
 */
#include "stm32f1xx_hal.h"
#include "Motor_DC.h"

extern TIM_HandleTypeDef htim1;
extern TIM_HandleTypeDef htim2;

// Dinh nghia chan CH1 va CH2 hai kenh ben trai de chon chay thuan hay chay nghich.
#define DC_LEFT_CH1_PORT    GPIOB
#define DC_LEFT_CH1_PIN     GPIO_PIN_12
#define DC_LEFT_CH2_PORT    GPIOB
#define DC_LEFT_CH2_PIN     GPIO_PIN_13
// Dinh nghia chan CH1 va CH2 hai kenh ben phai de chon chay thuan hay chay nghich.
#define DC_RIGHT_CH1_PORT   GPIOB
#define DC_RIGHT_CH1_PIN    GPIO_PIN_1
#define DC_RIGHT_CH2_PORT   GPIOB
#define DC_RIGHT_CH2_PIN    GPIO_PIN_10

//DINH NGHIA KENH TRAI
#define DC_PWM_1 &htim1
#define DC_PWM_2 &htim2
#define DC_MOTOR_CHANNEL_1  TIM_CHANNEL_1
#define DC_MOTOR_CHANNEL_2  TIM_CHANNEL_4

//Ham cho phep chay thuan cho hai dong co ben trai.

void DC_RIGHT_DOWN(void){
	HAL_GPIO_WritePin(DC_LEFT_CH1_PORT,DC_LEFT_CH1_PIN,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(DC_LEFT_CH2_PORT,DC_LEFT_CH2_PIN,GPIO_PIN_SET);
}

void DC_RIGHT_UP(void){
	HAL_GPIO_WritePin(DC_LEFT_CH1_PORT,DC_LEFT_CH1_PIN,GPIO_PIN_SET);
	HAL_GPIO_WritePin(DC_LEFT_CH2_PORT,DC_LEFT_CH2_PIN,GPIO_PIN_RESET);
}

void DC_LEFT_UP(void){
	//HAL_GPIO_WritePin(DC_RIGHT_CH1_PORT,DC_RIGHT_CH1_PIN,GPIO_PIN_RESET);
	//HAL_GPIO_WritePin(DC_RIGHT_CH2_PORT,DC_RIGHT_CH2_PIN,GPIO_PIN_SET);
	HAL_GPIO_WritePin(DC_RIGHT_CH1_PORT,DC_RIGHT_CH1_PIN,GPIO_PIN_SET);
	HAL_GPIO_WritePin(DC_RIGHT_CH2_PORT,DC_RIGHT_CH2_PIN,GPIO_PIN_RESET);
}

void DC_LEFT_DOWN(void){
	//HAL_GPIO_WritePin(DC_RIGHT_CH1_PORT,DC_RIGHT_CH1_PIN,GPIO_PIN_SET);
	//HAL_GPIO_WritePin(DC_RIGHT_CH2_PORT,DC_RIGHT_CH2_PIN,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(DC_RIGHT_CH1_PORT,DC_RIGHT_CH1_PIN,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(DC_RIGHT_CH2_PORT,DC_RIGHT_CH2_PIN,GPIO_PIN_SET);
}

void ROBOT_Forward(void){


	DC_LEFT_DOWN();
	DC_RIGHT_DOWN();

	__HAL_TIM_SET_COMPARE(DC_PWM_1,DC_MOTOR_CHANNEL_1, 50); // PWM1
	__HAL_TIM_SET_COMPARE(DC_PWM_2,DC_MOTOR_CHANNEL_2, 50); //PWM2
}

void ROBOT_Backward(void){
	DC_LEFT_UP();
	DC_RIGHT_UP();

	__HAL_TIM_SET_COMPARE(DC_PWM_1,DC_MOTOR_CHANNEL_1, 50); // PWM1
	__HAL_TIM_SET_COMPARE(DC_PWM_2,DC_MOTOR_CHANNEL_2, 50); //PWM2
}
void ROBOT_TurnLeft(void){
	DC_LEFT_DOWN();
    DC_RIGHT_UP();
    __HAL_TIM_SET_COMPARE(DC_PWM_1,DC_MOTOR_CHANNEL_1, 50); // PWM1
	__HAL_TIM_SET_COMPARE(DC_PWM_2,DC_MOTOR_CHANNEL_2, 50); //PWM2
		// PWM1;
		//PWM2;
}
void ROBOT_TurnRight(void){
	DC_LEFT_UP();
	DC_RIGHT_DOWN();
	__HAL_TIM_SET_COMPARE(DC_PWM_1,DC_MOTOR_CHANNEL_1, 50); // PWM1
	__HAL_TIM_SET_COMPARE(DC_PWM_2,DC_MOTOR_CHANNEL_2, 50); //PWM2
	// PWM1;
	//PWM2;
}
void ROBOT_Stop(void){
	__HAL_TIM_SET_COMPARE(DC_PWM_1,DC_MOTOR_CHANNEL_1, 0);
	__HAL_TIM_SET_COMPARE(DC_PWM_2,DC_MOTOR_CHANNEL_2, 0);
	HAL_GPIO_WritePin(DC_LEFT_CH1_PORT,DC_LEFT_CH1_PIN,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(DC_LEFT_CH2_PORT,DC_LEFT_CH2_PIN,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(DC_RIGHT_CH1_PORT,DC_RIGHT_CH1_PIN,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(DC_RIGHT_CH2_PORT,DC_RIGHT_CH2_PIN,GPIO_PIN_RESET);
}
